title: Portfolio Hamza Atig
email: hamza.atig@gmail.com
description: >-
  Portfolio professionnel d'Hamza Atig — Architecte Java/Cloud

baseurl: "/atig-hamza-portfolio-"
url: "https://hamzaatig.github.io"


# Thème par défaut
theme: minima

# Plugins autorisés par GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-optional-front-matter
  - jekyll-assets
  - jekyll-remote-theme