title: Hamza Atig
email: hamza.atig@gmail.com
description: >-
  Portfolio professionnel d'Hamza Atig — Architecte solutions & securite cloud
baseurl: "/atig-hamza-portfolio-"
url: "https://hamzaatig.github.io"

theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
